name = "tic-tac-toe"
main = "src/index.ts"
compatibility_date = "2025-10-04"

[durable_objects]
bindings = [
  { name = "GAME", class_name = "Game" }
]

[assets]
directory = "./dist"
binding = "ASSETS"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["Game"]
